# Generated by Django 5.2.6 on 2025-11-27 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Myidea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название идеи"),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные комментарии к идее",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "pictures",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите визуализацию идеи",
                        null=True,
                        upload_to="idea/photos/",
                        verbose_name="Фото/Схема",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Поделиться идеей с сообществом",
                        verbose_name="Публичная идея",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("business", "💼 Бизнес"),
                            ("creative", "🎨 Творчество"),
                            ("technology", "💻 Технологии"),
                            ("improvement", "🔧 Улучшение"),
                            ("personal", "👤 Личное"),
                            ("other", "🔷 Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "🆕 Новая"),
                            ("in_progress", "🔄 В работе"),
                            ("completed", "✅ Реализована"),
                            ("postponed", "⏸️ Отложена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую",
                        max_length=200,
                        null=True,
                        verbose_name="Теги",
                    ),
                ),
                (
                    "estimated_effort",
                    models.CharField(
                        blank=True,
                        help_text="Например: 2 недели, 1 месяц и т.д.",
                        max_length=50,
                        null=True,
                        verbose_name="Оценка усилий",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "public_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideas",
                        to="publications.publicpost",
                        verbose_name="Публикация в ленте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Идея",
                "verbose_name_plural": "Идеи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "status"],
                        name="idea_myidea_owner_i_e883bd_idx",
                    ),
                    models.Index(
                        fields=["is_public", "status"],
                        name="idea_myidea_is_publ_801669_idx",
                    ),
                    models.Index(
                        fields=["category"], name="idea_myidea_categor_ca954a_idx"
                    ),
                ],
            },
        ),
    ]
