# Generated by Django 5.2.6 on 2025-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Myidea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Коментарий"),
                ),
                (
                    "pictures",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите картинки своих мыслей",
                        null=True,
                        upload_to="media/photos",
                        verbose_name="Фото",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления момента"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Интересные мысли можно публиковать в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "notification_task_id",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="id задачи уведомления",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
