# Generated by Django 5.2.6 on 2025-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myidea",
            name="notification_task_id",
        ),
        migrations.AlterField(
            model_name="myidea",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления мыслей"
            ),
        ),
    ]
