# Generated by Django 5.2.6 on 2025-11-27 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Moment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название момента"),
                ),
                (
                    "comments",
                    models.TextField(
                        help_text="Опишите что это за момент и почему он важен",
                        verbose_name="Описание момента",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото момента",
                        null=True,
                        upload_to="media/photos/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите видео момента",
                        null=True,
                        upload_to="media/videos/",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Где произошел этот момент",
                        max_length=100,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Поделиться моментом с сообществом",
                        verbose_name="Публичный момент",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "😊 Счастливый"),
                            ("excited", "🎉 Восторг"),
                            ("peaceful", "😌 Спокойный"),
                            ("inspired", "💡 Вдохновение"),
                            ("proud", "🏆 Гордость"),
                            ("grateful", "🙏 Благодарность"),
                            ("funny", "😄 Смешной"),
                            ("other", "🔷 Другой"),
                        ],
                        default="happy",
                        max_length=20,
                        verbose_name="Настроение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nature", "🌳 Природа"),
                            ("travel", "✈️ Путешествия"),
                            ("family", "👨\u200d👩\u200d👧\u200d👦 Семья"),
                            ("friends", "👫 Друзья"),
                            ("achievement", "🏅 Достижение"),
                            ("celebration", "🎊 Праздник"),
                            ("daily", "📅 Повседневность"),
                            ("creative", "🎨 Творчество"),
                            ("other", "🔷 Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Когда произошел этот момент",
                        verbose_name="Дата события",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую",
                        max_length=200,
                        null=True,
                        verbose_name="Теги",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "public_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moments",
                        to="publications.publicpost",
                        verbose_name="Публикация в ленте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Момент",
                "verbose_name_plural": "Моменты",
                "ordering": ["-event_date"],
                "indexes": [
                    models.Index(
                        fields=["owner", "event_date"],
                        name="moments_mom_owner_i_d26186_idx",
                    ),
                    models.Index(
                        fields=["is_public", "event_date"],
                        name="moments_mom_is_publ_69f01c_idx",
                    ),
                    models.Index(
                        fields=["category", "mood"],
                        name="moments_mom_categor_e0c86a_idx",
                    ),
                ],
            },
        ),
    ]
