# Generated by Django 5.2.6 on 2025-10-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moment",
            name="notification_task_id",
        ),
    ]
