# Generated by Django 5.2.6 on 2025-11-27 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=30,
                        verbose_name="Место",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото интересного события",
                        null=True,
                        upload_to="media/photos/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите видео интересного события",
                        null=True,
                        upload_to="media/videos/",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "date_deadline",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Дата, когда необходимо выполнять привычку",
                        verbose_name="Дата выполнения привычки",
                    ),
                ),
                (
                    "time_deadline",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку",
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка",
                        max_length=50,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Привычка, способ вознаградить себя за выполнение полезной привычки",
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания в днях",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Вознаграждение за выполнение привычки",
                        max_length=50,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Время, которое предположительно нужно потратить на выполнение привычки. Укажите в минутах",
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telegram Chat ID",
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="Уведомление отправлено"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Признак активности"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "public_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="publications.publicpost",
                        verbose_name="Публикация в ленте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["id"],
            },
        ),
    ]
