# Generated by Django 5.2.6 on 2025-10-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Коментарий"),
        ),
        migrations.AddField(
            model_name="habit",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото интересного события",
                null=True,
                upload_to="media/photos",
                verbose_name="Фото",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Загрузите видео интересного события",
                null=True,
                upload_to="media/videos",
                verbose_name="Видео",
            ),
        ),
    ]
