# Generated by Django 5.2.6 on 2025-10-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_comments_habit_photo_habit_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="notification_sent",
            field=models.BooleanField(
                default=False, verbose_name="Уведомление отправлено"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
