# Generated by Django 5.2.6 on 2025-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_notification_sent_habit_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_enjoyable",
            field=models.BooleanField(
                blank=True,
                help_text="Привычка, способ вознаградить себя за выполнение полезной привычки",
                null=True,
                verbose_name="Признак приятной привычки",
            ),
        ),
    ]
