# Generated by Django 5.2.6 on 2025-11-27 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Заголовок цели"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото своей цели",
                        null=True,
                        upload_to="media/photos/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите видео своей цели",
                        null=True,
                        upload_to="media/videos/",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения цели",
                        max_length=30,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Отображать цель в публичной ленте",
                        verbose_name="Публичная цель",
                    ),
                ),
                (
                    "notification_task_id",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="ID задачи уведомления",
                    ),
                ),
                (
                    "date_deadline",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Дата, когда необходимо выполнить цель",
                        verbose_name="Дата выполнения",
                    ),
                ),
                (
                    "time_deadline",
                    models.TimeField(
                        blank=True,
                        help_text="Время, когда необходимо выполнить цель",
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Конкретное действие для достижения цели",
                        max_length=50,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_progress",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Признак достижения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная цель"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "🟢 Низкий"),
                            ("medium", "🟡 Средний"),
                            ("high", "🔴 Высокий"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "❤️ Здоровье"),
                            ("education", "🎓 Обучение"),
                            ("career", "💼 Карьера"),
                            ("finance", "💰 Финансы"),
                            ("relationships", "👥 Отношения"),
                            ("hobby", "🎨 Хобби"),
                            ("travel", "✈️ Путешествия"),
                            ("other", "🔷 Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "public_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="publications.publicpost",
                        verbose_name="Публикация в ленте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active"],
                        name="goal_goal_owner_i_3b1695_idx",
                    ),
                    models.Index(
                        fields=["is_public", "is_active"],
                        name="goal_goal_is_publ_1e2adc_idx",
                    ),
                    models.Index(
                        fields=["date_deadline"], name="goal_goal_date_de_5f405d_idx"
                    ),
                ],
            },
        ),
    ]
