# Generated by Django 5.2.6 on 2025-09-26 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Коментарий"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото своей цели",
                        null=True,
                        upload_to="media/photos",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите видео своей цели",
                        null=True,
                        upload_to="media/videos",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Укажите место своей цели",
                        max_length=30,
                        verbose_name="Место",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления момента"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Интересные цели можно публиковать в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "notification_task_id",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="id задачи уведомления",
                    ),
                ),
                (
                    "date_deadline",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Дата, когда необходимо выполнять цель",
                        verbose_name="Дата выполнения цели",
                    ),
                ),
                (
                    "time_deadline",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять цель",
                        verbose_name="Время выполнения цели",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка",
                        max_length=50,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_progress",
                    models.BooleanField(
                        help_text="Достижение цели", verbose_name="Признак достижения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Признак активности"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
