# Generated by Django 5.2.6 on 2025-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="action",
            field=models.CharField(
                help_text="Действие, которое представляет собой цель",
                max_length=50,
                verbose_name="Действие",
            ),
        ),
    ]
