# Generated by Django 5.2.6 on 2025-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0003_alter_goal_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="Действие, которое представляет собой цель",
                max_length=50,
                null=True,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="is_progress",
            field=models.BooleanField(
                blank=True,
                help_text="Достижение цели",
                null=True,
                verbose_name="Признак достижения",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Укажите место своей цели",
                max_length=30,
                null=True,
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="time_deadline",
            field=models.TimeField(
                blank=True,
                help_text="Время, когда необходимо выполнять цель",
                null=True,
                verbose_name="Время выполнения цели",
            ),
        ),
    ]
