# Generated by Django 5.2.6 on 2025-11-17 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("habit", "Привычка"),
                            ("goal", "Цель"),
                            ("idea", "Идея"),
                            ("moment", "Момент"),
                        ],
                        max_length=20,
                        verbose_name="Тип записи",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "telegram_message_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID сообщения в Telegram"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Публичная запись",
                "verbose_name_plural": "Публичные записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
